// <auto-generated />
using System;
using LaborDoctor.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaborDoctor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LaborDoctor.API.Models.ClinicaModel", b =>
                {
                    b.Property<int>("id_clinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("varchar(19)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome_fantasia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha_antiga")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_clinica");

                    b.ToTable("tb_clinica");

                    b.HasData(
                        new
                        {
                            id_clinica = 1,
                            cnpj = "11.777.5555/0001-99",
                            email = "root",
                            nome = "root Clinica",
                            nome_fantasia = "root Clinica",
                            senha = "$2a$11$19BcqD1injq6X4b0kjoIheO7ZVLQOlNEZR3h53JUWX2p0cBKM1cb.",
                            senha_antiga = "$2a$11$eBC.zEW1SYnM8Ai5J3.oFOfmicATeCxoKwikdzqcrP94Xnm6Wh10m",
                            telefone = "(45) 96666-1234"
                        },
                        new
                        {
                            id_clinica = 2,
                            cnpj = "10.136.4860/0001-85",
                            email = "gndi@clinica.com",
                            nome = "GNDI",
                            nome_fantasia = "GNDI",
                            senha = "$2a$11$FsPKSrUlgkBEwNiJvmsEaeZiqBa/zNzUBFD2fpU8G3oUMvYmzlEhS",
                            senha_antiga = "$2a$11$Z9XDi7rBlbZPkQnKKVzDOudp8p0RlBQK1eljSHxWFgOgj6SoajeYK",
                            telefone = "(11) 98524-5698"
                        });
                });

            modelBuilder.Entity("LaborDoctor.API.Models.ConsultaModel", b =>
                {
                    b.Property<int>("id_consulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("id_medico")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("id_paciente")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("id_schedule")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id_consulta");

                    b.HasIndex("id_medico");

                    b.HasIndex("id_paciente");

                    b.HasIndex("id_schedule");

                    b.ToTable("tb_consulta");
                });

            modelBuilder.Entity("LaborDoctor.API.Models.MedicoModel", b =>
                {
                    b.Property<int>("id_medico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("crm")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_medico");

                    b.ToTable("tb_medico");

                    b.HasData(
                        new
                        {
                            id_medico = 1,
                            cpf = "12345678910",
                            crm = "045465/SP",
                            email = "rodrignucleo@labordoctor.com",
                            nome = "Rodrigo Ribeiro",
                            telefone = "11992668225"
                        },
                        new
                        {
                            id_medico = 2,
                            cpf = "98765412398",
                            crm = "221748/PR",
                            email = "patricia.oliveira@labordoctor.com",
                            nome = "Patricia Oliveira",
                            telefone = "9899265826597"
                        });
                });

            modelBuilder.Entity("LaborDoctor.API.Models.PacienteModel", b =>
                {
                    b.Property<int>("id_paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha_antiga")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_paciente");

                    b.ToTable("tb_paciente");

                    b.HasData(
                        new
                        {
                            id_paciente = 1,
                            cpf = "111.222.333-44",
                            email = "root",
                            nome = "root Paciente",
                            senha = "$2a$11$2lFVphB3ncST3EityNCBj.CFzfzb70LUyRQJlL6B2G/sKwUHYKPku",
                            senha_antiga = "$2a$11$fnBFJAQGooSZIf.gaoa1keUbQkzStpNjNtRan.LnBj/ptag188GyO",
                            telefone = "(45) 96666-1234"
                        },
                        new
                        {
                            id_paciente = 2,
                            cpf = "987.458.236-98",
                            email = "estevao@labordoctor.com",
                            nome = "Estevão Rocha",
                            senha = "$2a$11$6CGChrSicZCdxGRKImWO4u4rpbR9fUgkbHCw8EbgsDuqr/77nfm5i",
                            senha_antiga = "$2a$11$JnEILtUHKQtyOmbAG9yl0OfsqmjeiaaJN8RZX5r96fIlCQ.U6aSue",
                            telefone = "(11) 99478-5200"
                        });
                });

            modelBuilder.Entity("LaborDoctor.API.Models.ScheduleModel", b =>
                {
                    b.Property<int>("id_schedule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("data")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("id_medico")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_schedule");

                    b.HasIndex("id_medico");

                    b.ToTable("tb_schedule");
                });

            modelBuilder.Entity("LaborDoctor.API.Models.ConsultaModel", b =>
                {
                    b.HasOne("LaborDoctor.API.Models.MedicoModel", "medico")
                        .WithMany()
                        .HasForeignKey("id_medico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaborDoctor.API.Models.PacienteModel", "paciente")
                        .WithMany()
                        .HasForeignKey("id_paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaborDoctor.API.Models.ScheduleModel", "schedule")
                        .WithMany()
                        .HasForeignKey("id_schedule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medico");

                    b.Navigation("paciente");

                    b.Navigation("schedule");
                });

            modelBuilder.Entity("LaborDoctor.API.Models.ScheduleModel", b =>
                {
                    b.HasOne("LaborDoctor.API.Models.MedicoModel", "medico")
                        .WithMany()
                        .HasForeignKey("id_medico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medico");
                });
#pragma warning restore 612, 618
        }
    }
}
